version: '2'
services:
  allure-server:
    container_name: allure-server
    image: kochetkovma/allure-server:latest
    ports:
      - 5050:5050
    volumes:
      - /allure-server-store:/allure
  c-icap:
    container_name: c-icap-client
    image: glasswallsolutions/c-icap-client:manual-v1
  codecept:
    build:
      context: ..
      dockerfile: docker/codecept.Dockerfile
    container_name: codeceptjs
    user: ${USER_ID}
    network_mode: host
    environment:
      - NO_OF_WORKERS=10
      - CODECEPT_ARGS=--debug
    volumes:
     - ../:/tests