version: '3'
services:
  allure-server:
    container_name: allure-server
    image: kochetkovma/allure-server:latest
    ports:
      - 5050:5050
    volumes:
      - /allure-server-store:/allure
  codecept:
    build:
      context: ..
      dockerfile: docker/codecept.Dockerfile
    container_name: codeceptjs
    user: ${USER_ID}
    network_mode: host
    environment:
      - NO_OF_WORKERS=10
      - CODECEPT_ARGS=--debug
    volumes:
     - ../:/tests
    extra_hosts:
    - "saaspoc1.sharepoint.com:34.244.17.60"
    - "ukc-word-edit.officeapps.live.com:34.244.17.60"
    - "saaspoc1-my.sharepoint.com:34.244.17.60"
    - "ukc-excel.officeapps.live.com:34.244.17.60"
    - "ukc-powerpoint.officeapps.live.com:34.244.17.60"
    - "browser.pipe.aria.microsoft.com:34.244.17.60"
   