version: '2'
services:
  allure-server:
    container_name: allure-server
    #    build: . # Local debug
    image: kochetkovma/allure-server:latest
    #    environment: # Local debug
    #      ALLURE_REPORT_URL_BASE: http://test.ru/ # Local debug
    ports:
      - 8080:8080
    volumes:
      - /allure-server-store:/allure
  codecept:
    build:
      context: ..
      dockerfile: docker/codecept.Dockerfile
    container_name: codeceptjs
    user: ${USER_ID}
    network_mode: host
    volumes:
     - ../:/tests